-- dhar mann title generator 

optionalAdvertisement = true -- please keep on :sob: 

-- words to pick from (had to clean it up for papa roblox)
-- also this is copied pasted from my python thing HAHAHA
wordsOne = {
	"Kid",
	"Adult",
	"Man",
	"Mean Person",
	"Felon",
	"Teacher",
	"Karen",
	"Woman",
	"Boy",
	"Friend",
	"President",
	"Best Friend",
	"Fake Friend",
	"Nerd",
	"Rich person",
	"Poor person",
	"Fake instagrammer",
	"Judge",
	"Lawyer",
	"Vice President",
	"Idiot",
	"Mentally Challenged Person",
	"Robot",
	"Wall-E",
	"SsSniper Wolf",
	"Dhar Man",
	"Flamingo",
	"DanTDM",
	"YouTuber",
	"Black fellow",
	"Famous guy",
	"Roblox Player",
	"Slender",
	"The Imposter",
	"The Imposter From Among Us",
	"The Crewmate",
	"The Crewmate from Among Us",
	"Bob"
}

wordsTwo = {
	"Kills",
	"Makes Fun Of",
	"Punches",
	"Convicts",
	"Steals",
	"Robs",
	"Destroys",
	"Burns",
	"Kicks",
	"Locks in basement",
	"Tears apart",
	"Eats",
	"Fat shames",
	"Bullies",
	"Judges",
	"Escapes",
	"Dodges",
	"Dunks",
	"Shames",
	"Looks at",
	"Consumes",
	"Shocks"
}

wordsFour = {
	"Instantly regrets it",
	"What happens next is shocking",
	"Lives to regret it",
	"Gets convicted",
	"Gets sent to jail",
	"Gets sent to jail for 500 years",
	"Instantly dies",
	"Gets killed by karma instantly",
	"Falls off a cliff",
	"Gets run over by a tractor",
	"Gets awarded",
	"Gets a prize",
	"Gets the Noble Peace Prize",
	"Buys a chicken",
	"Dies",
	"Dies, but then comes back alive then dies again",
	"Gets burned alive",
	"Dies from a toaster",
	"Does not live to regret it",
	"Falls into the river and dies",
	"Becomes the president",
}

-- pick the random 
randomthing = ""..wordsOne[math.random(1, #wordsOne)].." "..wordsTwo[math.random(1, #wordsTwo)].." "..wordsOne[math.random(1, #wordsOne)]..", "..wordsFour[math.random(1, #wordsFour)].."!" -- this was the most painful thing to write in synx code editor


if optionalAdvertisement == true then 
	game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(randomthing.." Generated by Garfield's Dhar Man Title Generator", "All")
else 
	game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(randomthing, "All")
end 
